//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@MainActor
struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        TitleSlide()
        SelfIntroSlide()
        CenterSlide("今回はSwiftUIのアニメーションについて")
        DenaEventSlide()
        DenaEventContentsSlide(isActive: false, isAnimatable: false)
        CenterSlide("0 → 100 が 浮き上がるような \n アニメーション になる😭")
        FailMethodSlide()
        KoshimizuSanSlide()
        WhatsAnimatableSlide()
        SuccessMethodSlide()
        CenterSlide("上手くいった👏")
        DenaEventContentsSlide(isActive: true, isAnimatable: true)
        CenterSlide("Pathを使ったアニメーションの時は\nどうなるの🤔")
        PathSlide()
        WhatsShapeSlide()
        WhatsShapeSlide(onTaped: true)
        ShapeSuccessSlide()
        CenterSlide("Shapeを他にも使うと")
        GeocentrismSlide()
        CenterSlide("あなたも、これで快適なSwiftUIライフを")
        CenterSlide("Fin.")
//        CenterSlide("上手くいった👏")
    }
}
