//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@MainActor
struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        
        TitleSlide()
        SelfIntroSlide()
        CenterSlide("今回はSwiftUIのアニメーションについて")
        CenterSlide("3月7日 とあるイベントにて、、、")
        DenaEventSlide(isActive: false, isAnimatable: false)
        CenterSlide("0 → 100 が 浮き上がるような \n アニメーション になる😭")
        
        
        DenaEventSlide(isActive: true, isAnimatable: true)
    }
}
